README.md, lib/mock.ex
The readme references a `:_` which is no longer in the actual example (changed in f3f37e61867922aba857d51482b2aa9b8c0c2823).
The referenced `:_` argument confused me and apparently other people as well (see #31), so re-adding it in the example instead of removing it from the description seemed like the right way to go.
I also removed some typo's and whitespace issues I ran into.
=> Readme cleanup

test/mock_test.exs
test/mock_test.exs:32: warning: variable x is unused
=> tests: fix variable not used warning

.gitignore, .travis.yml, README.md, mix.exs, mix.lock
Mock has 100% test coverage - sadly you don't
see something like that everywhere.
lets make it more visible and make sure it stays at 100% :)
for this to work it is required to enable coveralls for this repo on https://coveralls.io
=> Adds coveralls to the project

mix.exs, mix.lock
https://github.com/eproxus/meck/issues/179 was fixed in the most recent meck release, this should unbreak mock for users with elixir 1.5 / OTP 20
meck PR here: https://github.com/eproxus/meck/pull/180
=> upgrade meck to 0.8.8

README.md, lib/mock.ex, test/mock_test.exs
I added example how to use Mock to mock functions with same name and different arities and replaced HashDict -> Map to fix compile warnings, since HashDict is deprecating.
=> Add multiple arity example and fix warnings

README.md
0.2.x does not include methods described in Readme like: #setup_with_mocks
=> Bump package version in README.md

lib/mock.ex, test/mock_test.exs
Fixes #78.
Defines an assertion which displays calls actually made when it fails. Example:
```
defmodule Example do
use ExUnit.Case
import Mock
test "example" do
with_mock String,
[reverse: fn(x) -> 2*x end,
length: fn(_x) -> :ok end] do
String.reverse(3)
assert_called(String.reverse(3))
#
#
#
assert_called(String.reverse(2))
end
end
end
```
=> Implement assert_called as first class assertion, displays calls on failure

README.md
The documentation link in the README seems to be broken, so I pointed it to the hex docs instead.
=> point documentation link to hex

lib/mock.ex
The underlying `meck` function supports wildcard matching by passing in the `:_` atom. Very handy, let's document it!
https://hexdocs.pm/meck/meck.html#called-4
=> Documentation for wildcard matches in called/1 and assert_called/1

.travis.yml, mix.exs, mix.lock
Upgrades meck from 0.8.8 to 0.8.13.
Adds support for OTP 21 and elixir 1.8.
Adds Elixir 1.8 to CI.
Closes https://github.com/jjh42/mock/issues/96.
=> Upgrade meck from 0.8.8 to 0.8.13

lib/mock.ex
When running tests using `setup_with_mock` the mocks aren't actually unloaded fast enough (or maybe not at all) and sometimes they pass through to other tests (which don't want the mocks to be active at all). All the tests I did were on `async: false` and this still happened. Then I noticed you don't unload explicitly the mocks so hence the PR. I unload the mocks globally using `:meck.unload()` but I figure you don't want to use the mocks in different tests (setting them in one test and unloading in different) as the loading/unloading is indeterministic. I'm convinced it's pretty safe to unload all the mocks at the end of the test every time the test is finished. This happens in ExUnit's `on_exit`.
=> :meck.unload on exit

lib/mock.ex
Indent the example, so that it gets marked up as a code block.
=> Fix docstring markup for with_mocks

README.md, test/mock_test.exs
Documentation and test update for [Issue 80](https://github.com/jjh42/mock/issues/80).
This PR updates the `README` example for input-dependent returns. The original example was calling `with_mocks`, when it needed to call `with_mock` (singular). The new example uses `Map` so that it doesn't rely on `HTTPotion`. I also added this example to the test files, to verify that it compiles and passes.
=> [Issue 80] Update README with working input-dependent returns.

lib/mock.ex, test/mock_test.exs
As this is a thin wrapper, it doesn't perform any checks and has the same syntax of wrapping args in `[]`.
Better macro that is available only inside anonymous mock functions and has nicer syntax for args could theoretically be possible, but would require much more work and will be much harder to maintain.
If you are interestered in that kind of macro, let me know - I can try and spend some time implementing it.
=> add a thin wrapper around :meck.passthrough

README.md
This PR adds a few examples for advanced pattern matching usage with `assert_called`.
Inspired by [this](https://github.com/jjh42/mock/issues/109#issuecomment-561913834) issue thread.
=> docs: add pattern matching examples for assert_called

README.md
Missed a `with_mock` block in https://github.com/jjh42/mock/pull/112 ☹️
=> docs: add missing `with_mock` block

lib/mock.ex
The `{get: fn ...` is invalid. This was probably some typo.
=> Remove extra curly brackets in with_mocks

README.md, lib/mock.ex
I couldn't find any other Elixir reference for this, so I thought I'd expose `meck.history` for this.
=> Asserting function call order

README.md, lib/mock.ex, test/mock_test.exs
I've added the `assert_called_exactly` assertation which is related to what was proposed here https://github.com/jjh42/mock/issues/116 inspired by RSpec Mocks.
=> add assert_called_exactly

README.md
I had the very case that I included as a bullet point in the docs. I didn't see an obvious way to do it with Mock because the examples were assuming you wanted to mock based on the exact input value. I wanted to mock based on parts of the input value. I figured out how to do it with Mock and thought it would be helpful for others to have explicit docs around this.
Happy to change any of the language. Thanks for the great library.
=> Docs around mocking based on parts of the input

lib/mock.ex
Fix typo for `call_history` doc in the Mock module.
=> Fix typo for `call_history` doc in the Mock module.

README.md, lib/mock.ex, test/mock_test.exs
This adds a new macro/function to let us make sure a function was called **at_least** n number of times
=> Added new function/macro to allow for "at_least" test
